# Generated by Django 4.2.5 on 2023-11-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homework_images/')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='homework_app.homework')),
            ],
        ),
    ]
