# Generated by Django 4.2.5 on 2023-11-21 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0003_studentteacherconfirm_studentteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
