# Generated by Django 4.2.5 on 2023-11-24 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0005_assignmentresult_delete_homeworkresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerPairResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentPair', to='homework_app.assignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairResult', to='homework_app.questionanswerpair')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionResult', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
