# Generated by Django 4.2.5 on 2023-12-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0006_questionanswerpairresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
