# Generated by Django 4.2.5 on 2024-01-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0007_customuser_gender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
