# Generated by Django 4.2.5 on 2024-01-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerpair',
            name='qtype',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionanswerpair',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='homework_app.questionanswerpair')),
            ],
        ),
        migrations.AddField(
            model_name='questionanswerpair',
            name='correct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qapair', to='homework_app.option'),
        ),
    ]
