# Generated by Django 4.2.5 on 2024-01-21 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0010_questioncorrectoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswerpairresult',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='QuestionSelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionselectass', to='homework_app.assignment')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionqselect', to='homework_app.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionoselect', to='homework_app.questionanswerpair')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionselect', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
