# Generated by Django 4.2.5 on 2024-02-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0012_remove_class_teacher_class_school_school_license_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='homework_app.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='license_end',
            field=models.DateField(),
        ),
    ]
