# Generated by Django 4.2.5 on 2024-03-22 11:18

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0014_remove_questionanswerpair_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentteacher',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentteacher',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentteacherconfirm',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentteacherconfirm',
            name='teacher',
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='school',
        ),
        migrations.AddField(
            model_name='customuser',
            name='classs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_classs', to='homework_app.class'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
        migrations.DeleteModel(
            name='StudentTeacher',
        ),
        migrations.DeleteModel(
            name='StudentTeacherConfirm',
        ),
    ]
