# Generated by Django 4.2.5 on 2024-03-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0015_remove_studentteacher_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_school', to='homework_app.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='classs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_classs', to='homework_app.class'),
        ),
    ]
